/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SinhVienCNTTvaKinhTe;

import static java.lang.module.ModuleDescriptor.read;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Viet Duc
 */
public class Quanlydiem extends javax.swing.JFrame {
        DefaultTableModel dtm;
        Quanlysinhviencongnghevakinhte a = new Quanlysinhviencongnghevakinhte();
        public Quanlydiem() {
        initComponents();
        dtm= new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"maSV","Ho ten", "gioi tinh", "diem1", "diem2"} );
        jTable1.setModel(dtm);
        setLocationRelativeTo(null);
        }
        
    public void loadDuLieu(ArrayList<Sinhvien> a1){
        ArrayList<Sinhvien> b= a.getA();
        while(dtm.getRowCount()>0) dtm.removeRow(0);
        for(Sinhvien y:b){
            if(y instanceof SVCNTT)
                dtm.addRow(new Object[]{y.getMa(),y.getHoten(),y.isGioitinh(),((SVCNTT) y).getJava(),((SVCNTT) y).getCss(),((SVCNTT) y).getHtml(),y.tinhDTB(),y.getXepLoai()});
            else 
                dtm.addRow(new Object[]{y.getMa(),y.getHoten(),y.isGioitinh(),((SVKInhte) y).getNLKT(),((SVKInhte) y).getMARKET(),y.tinhDTB(),y.getXepLoai()});
        }
    }

   
//    public void loaddulieu 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtma = new javax.swing.JTextField();
        txtNgaysinh = new javax.swing.JTextField();
        Txtgioitinh = new javax.swing.JTextField();
        TimSV = new javax.swing.JButton();
        DeleteSinhvien = new javax.swing.JButton();
        additionalSinhVien = new javax.swing.JButton();
        exitsSinhvien = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCNTT = new javax.swing.JButton();
        BtKinhte = new javax.swing.JButton();
        Lbdiem1 = new javax.swing.JLabel();
        Lbdiem2 = new javax.swing.JLabel();
        LbDiem3 = new javax.swing.JLabel();
        txtDiem1 = new javax.swing.JTextField();
        TxtDiem2 = new javax.swing.JTextField();
        TxtDiem3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtHovaten = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MÃ: ");

        txtma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaActionPerformed(evt);
            }
        });

        txtNgaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaysinhActionPerformed(evt);
            }
        });

        Txtgioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtgioitinhActionPerformed(evt);
            }
        });

        TimSV.setText("Tìm sinh viên ");
        TimSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimSVActionPerformed(evt);
            }
        });

        DeleteSinhvien.setText("Xóa sinh viên ");
        DeleteSinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSinhvienActionPerformed(evt);
            }
        });

        additionalSinhVien.setText("Thêm sinh viên");
        additionalSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionalSinhVienActionPerformed(evt);
            }
        });

        exitsSinhvien.setText("Thoát ");
        exitsSinhvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitsSinhvienActionPerformed(evt);
            }
        });

        Save.setText("Lưu");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Ngày sinh: ");

        jLabel3.setText("Giới tính:");

        jLabel4.setText("Sinh Viên Khoa: ");

        btCNTT.setText("CNTT");
        btCNTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCNTTActionPerformed(evt);
            }
        });

        BtKinhte.setText("Kinh Te");
        BtKinhte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtKinhteActionPerformed(evt);
            }
        });

        Lbdiem1.setText("Điểm:");

        Lbdiem2.setText("Điểm: ");

        LbDiem3.setText("Điểm: ");

        TxtDiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDiem2ActionPerformed(evt);
            }
        });

        TxtDiem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDiem3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ", "Họ và tên", "Giới tính", "Điểm môn 1", "Điểm môn 2", "Điểm môn 3", "Xếp hạng", "Điểm Trung BÌnh"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Bảng Thông tin: ");

        jButton1.setText("Mở File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Họ và Tên: ");

        jLabel7.setText("QUẢN LÝ SINH VIÊN CÁC KHOA CÔNG NGHỆ THÔNG TIN VÀ KINH TẾ");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Lbdiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Lbdiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TxtDiem2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(LbDiem3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TxtDiem3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Txtgioitinh, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btCNTT)
                                            .addGap(18, 18, 18)
                                            .addComponent(BtKinhte))
                                        .addComponent(txtNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                                        .addComponent(txtHovaten)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(31, 31, 31))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(DeleteSinhvien)
                            .addGap(18, 18, 18)
                            .addComponent(TimSV)
                            .addGap(14, 14, 14)
                            .addComponent(additionalSinhVien)
                            .addGap(18, 18, 18)
                            .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exitsSinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtHovaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txtgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCNTT)
                        .addComponent(BtKinhte)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbdiem1)
                    .addComponent(txtDiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbdiem2)
                    .addComponent(TxtDiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDiem3)
                    .addComponent(TxtDiem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteSinhvien)
                    .addComponent(TimSV)
                    .addComponent(additionalSinhVien)
                    .addComponent(exitsSinhvien)
                    .addComponent(Save)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaActionPerformed

    private void txtNgaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaysinhActionPerformed

    private void TxtgioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtgioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtgioitinhActionPerformed

    private void DeleteSinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSinhvienActionPerformed
            // TODO add your handling code here:
            String ma= JOptionPane.showInputDialog("Nhập mã cần xóa: ");
        if(a.xoatheoma(ma)==true)
            loadDuLieu(a.getA());
        else JOptionPane.showConfirmDialog(null, "Không có "+ma+" trong danh sách");
            
    }//GEN-LAST:event_DeleteSinhvienActionPerformed

    private void BtKinhteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtKinhteActionPerformed
        // TODO add your handling code here:\\
        txtDiem1.setText("Nguyen ly ke toan: ");
        TxtDiem2.setText("marketing: ");
        TxtDiem3.setText("");
    }//GEN-LAST:event_BtKinhteActionPerformed

    private void btCNTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCNTTActionPerformed
        // TODO add your handling code here:
        txtDiem1.setText("java: ");
        TxtDiem2.setText("css: ");
        TxtDiem3.setText("html: ");
    }//GEN-LAST:event_btCNTTActionPerformed

    private void TxtDiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDiem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDiem2ActionPerformed

    private void TxtDiem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDiem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDiem3ActionPerformed

    private void additionalSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionalSinhVienActionPerformed
        // TODO add your handling code here:
                    String ma,hoten;
                    boolean gioitinh;
                    System.out.println("nhap ma sinh vien: ");
                    ma=txtma.getText();
                    System.out.println("Nhap ho ten sinh vien: ");
                    hoten= txtHovaten.getText();
                    System.out.println("Nhap gioi tinh: ");
                    gioitinh= Boolean.parseBoolean(Txtgioitinh.getText());
                    System.out.println("nhap diem: ");
                    double d1, d2;
                    d1=Double.parseDouble(txtDiem1.getText());
                    d2=Double.parseDouble(TxtDiem2.getText());
                    Sinhvien x;
                    if(btCNTT.isSelected()){
                        double d3= Double.parseDouble(TxtDiem3.getText());
                        x= new SVCNTT(d3, d3, d3, ma, hoten, gioitinh);
                    }else x= new SVKInhte(d2, d2, ma, hoten, gioitinh);   
    }//GEN-LAST:event_additionalSinhVienActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
          JFileChooser f= new JFileChooser();
        f.showSaveDialog(null);
        String tenFile=f.getSelectedFile().getPath();
        a.ghiFile(tenFile);
    }//GEN-LAST:event_SaveActionPerformed

    private void exitsSinhvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitsSinhvienActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitsSinhvienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               JFileChooser f= new JFileChooser();
        f.showOpenDialog(this);
        String tenFile= f.getSelectedFile().getPath();
        a.docFile(tenFile);
        loadDuLieu(a.getA());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TimSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimSVActionPerformed
        // TODO add your handling code here:
          String ma= JOptionPane.showInputDialog("Nhập mã cần tìm: ");
            if(a.timtheoma()==null)
            loadDuLieu(a.getA());
        else JOptionPane.showConfirmDialog(null, "Không có "+ma+" trong danh sách");
    }//GEN-LAST:event_TimSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlydiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quanlydiem().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtKinhte;
    private javax.swing.JButton DeleteSinhvien;
    private javax.swing.JLabel LbDiem3;
    private javax.swing.JLabel Lbdiem1;
    private javax.swing.JLabel Lbdiem2;
    private javax.swing.JButton Save;
    private javax.swing.JButton TimSV;
    private javax.swing.JTextField TxtDiem2;
    private javax.swing.JTextField TxtDiem3;
    private javax.swing.JTextField Txtgioitinh;
    private javax.swing.JButton additionalSinhVien;
    private javax.swing.JButton btCNTT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitsSinhvien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiem1;
    private javax.swing.JTextField txtHovaten;
    private javax.swing.JTextField txtNgaysinh;
    private javax.swing.JTextField txtma;
    // End of variables declaration//GEN-END:variables
}
